# Generated by Django 3.0.9 on 2020-08-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(default='', max_length=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=60)),
                ('manager', models.CharField(default='', max_length=60)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='cp.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cp', models.CharField(choices=[('CON', 'Concreto'), ('GRA', 'Graute'), ('ARG', 'Argamassa')], default='CON', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('numero_cp', models.PositiveIntegerField()),
                ('nota_fiscal', models.CharField(default='', max_length=50)),
                ('hora_da_usina', models.DateTimeField()),
                ('hora_da_moldagem', models.DateTimeField()),
                ('traco', models.DecimalField(decimal_places=3, max_digits=5)),
                ('abatimento', models.PositiveIntegerField()),
                ('local_da_aplicacao', models.CharField(default='', max_length=255)),
                ('aprovado', models.BooleanField(blank=True, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Obra')),
            ],
        ),
        migrations.CreateModel(
            name='CP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('idade_rompimento', models.PositiveSmallIntegerField()),
                ('data_rompimento', models.DateTimeField()),
                ('cp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cps', to='cp.CPGroup')),
            ],
        ),
    ]
